name: ${projectName}
main: com.spinalcraft.stopstart.Stopstart
version: ${projectVersion}

commands:
  stopstart:
    description: Restart the server.
    usage: /stopstart
    permission: stopstart.stopstart
    permission-message: No!