name: StopStart
main: com.spinalcraft.stopstart.StopStart
version: 1.0

commands:
  stopstart:
    description: Restart the server.
    usage: /stopstart
    permission: stopstart.stopstart
    permission-message: No!