name: Stopstart
main: com.spinalcraft.stopstart.Stopstart
version: 1.0

depend: [Spinalpack]

commands:
  stopstart:
    description: Restart the server.
    usage: /stopstart
    permission: stopstart.stopstart
    permission-message: No!